spring:
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER #关于swagger的
  datasource: #数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.14:3306/chat2thesis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

#当mapper.xml路径与mapper.java不一致时，需要去指定mapper.xml的路径位置。
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 7701
